### ISSUE TITLE
Implement Share-Buttons on Landingpage

### ISSUE THREAD

**Issue by m-kroener** [acebusters/landing-pages#56]
The easier it is to share, the higher the probability that sb will share

**Comment by troggy** [comment]
Added Likely buttons for blog posts. Can be used for any page.

# Basic usage example

https://github.com/acebusters/landing-pages/blob/fae887460c427f7193f46a0e24a33ec6db76ba52/_layouts/blog_post.html#L15-L20

# Customization

https://github.com/ilyabirman/Likely
