### ISSUE TITLE
Crowdsale Modal not opening on /home

### ISSUE THREAD

**Issue by m-kroener** [acebusters/landing-pages#93]
If you go to acebusters.com and click on the button "save your 33% discount", the modal is not showing up. 

But it works on /crowdsale

**Comment by troggy** [comment]
works for me. Can you please check the errors in bowser console @m-kroener ?

**Comment by m-kroener** [comment]
<img width="610" alt="bildschirmfoto 2017-10-06 um 17 05 37" src="https://user-images.githubusercontent.com/31517309/31284384-a64d2b4e-aab8-11e7-9a3e-e4f2851a4459.png">

**Comment by m-kroener** [comment]
does this help? 
Using Chrome on Desktop btw

**Comment by m-kroener** [comment]
I made a hard refresh of the page and now its working. False alarm, sorry!
